#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 22 10:29:56 2019

@author: vol35098
"""

import tkinter as tk
from tkinter import LabelFrame, Radiobutton, Entry, Label
import random

class Application(tk.Tk):
    name = 'Výpočet'
    
    
    def __init__(self):
        super().__init__(className=self.name)
        self.title(self.name)
        
        
        ###------FUNKCE------###
        self.funkceFrame = LabelFrame(self, text = "FUNKCE", padx=5, pady=5)
        self.funkceFrame.pack(anchor=tk.W)
        self.znamenkoVar= tk.StringVar()
        self.AVar = tk.StringVar()
        self.BVar = tk.StringVar()
        ###
        Radiobutton(self.funkceFrame, text = '+', variable=self.znamenkoVar, value='+').pack()
        Radiobutton(self.funkceFrame, text = '-', variable=self.znamenkoVar, value='-').pack()
        Radiobutton(self.funkceFrame, text = '*', variable=self.znamenkoVar, value='*').pack()
        Radiobutton(self.funkceFrame, text = '/', variable=self.znamenkoVar, value='/').pack()
        
        ###------FUNKCE------###
        
        ###------CISLA------###
        self.cisloFrame = LabelFrame(self,padx=5,pady=5)
        self.cisloFrame.pack(anchor=tk.W)
        ###
        self.cisloA = Entry(self.cisloFrame, state='readonly', width='3', 
                            textvariable=self.AVar)
        self.cisloA.grid(row=4, column=3)
        
        self.znamenko = Label(self.cisloFrame, textvariable=self.znamenkoVar, 
                              width='3')
        self.znamenko.grid(row=4, column=4)
        
        self.cisloB = Entry(self.cisloFrame, state='readonly', width='3', 
                            textvariable=self.BVar)
        self.cisloB.grid(row=4, column=5)
        
        self.rovnitko = Label(self.cisloFrame, text='=', width='3')
        self.rovnitko.grid(row=4, column=6)
        
        self.vysledek = Entry(self.cisloFrame, state='readonly', width='3')
        self.vysledek.grid(row=4, column=7)
        ###------CISLA------###
        
        ###------HODNOCENI------###
        self.hodnoceFrame = LabelFrame(self, text='HODNOCENÍ', padx=5, pady=5)
        self.funkceFrame.pack(anchor=tk.W)
        ###------HODNOCENI------###
        
        ###------PROMENA pro znaménko------###
        self.znamenkoVar.trace('w', self.novyPriklad)
   # def zmena(self, x, y, z):
            #pro výpočty
           #print(self.znamenkoVar.get())
    #        pass
         ###------PROMENA pro znaménko------###
    
    
    def novyPriklad(self, x, y, z):
        
        if self.znamenkoVar.get() == '+':
            self.A = random.randint(1, 99)
            self.B = random.randint(0,100 - self.A)
            self.vysledek = self.A + self.B
        
        
        if self.znamenkoVar.get() == '-':
            self.A = random.randint(1, 99)
            self.B = random.randint(1, self.A)
            self.vysledek = self.A - self.B
            
        if self.znamenkoVar.get() == '*':
            self.A = random.randint(1, 9)
            self.B = random.randint(1, 9)
            self.vysledek = self.A * self.B
            
        if self.znamenkoVar.get() == '/':
            self.A = random.randint(1, 9)
            self.B = random.randint(1, 9)
            self.vysledek = self.A * self.B
            
            
        self.AVar.set(self.A)
        self.BVar.set(self.B)
            
    
    
       
    
        
        
        
        
            
        
        
 
 










app = Application()
app.mainloop()